### ISSUE TITLE
Withdraw report

### ISSUE THREAD

**Issue by DavidAnderson684** [LoRexxar/CVE_Request#2]
Hi,

Now that I've documented for you why there is no vulnerability here (1. The description assumes that you will be able to do a path traversal, which according to the code is impossible and 2. The ability of a logged-in WordPress admin to upload files (or to completely destroy the WP install, if he wishes), is not a vulnerability, but a pre-existing capability for a logged-in WP admin), please can you withdraw the report and CVE number application?

Please can you do this swiftly? Once CVE numbers start showing up in automated tools, people start worrying. With over 1 million installs of UD, it would be very irresponsible to not withdraw this.

Thank you,
David

**Comment by LoRexxar** [comment]
Although you did not answer my question, but by default you are the developer of the WordPress plugin.

1、 First, I have made CVE i, CVE-2017-16870, CVE-2017-16871, the reason for the existence of loopholes I have described quite clearly.
2、 Second, as a security researcher, my goal is to investigate whether there are loopholes in the system, not all loopholes must be easy to apply!
3、 Finally, since you think what I said is not valid, plug-ins are not flawed, then you absolutely do not have to be so nervous.

I think as a developer, it's a good idea to be right about security (if you do not think this is a security issue, you can do nothing!), Competitive upload holes that can be verified and re-uploaded Ways to fix, SSRF loopholes can be limited by intranet requests to avoid security problems! Attackers can attack various devices within the network through SSRF loopholes, and I think I do not need to give you SSRF what is popular science!

**Comment by DavidAnderson684** [comment]
> not all loopholes must be easy to apply!

@LoRexxar It can't be applied at all, because before you get to the file moving, `wp_handle_upload()` is called, which checks filename patterns. A filename ending in .php will be rejected, and so the `rename()` can never be run on a .php file, contrary to your report.
